version: 0.2

env:
  variables:
    IMAGE_TAG: ""          # Optional override
    CONTAINER_NAME: ""     # Must match ECS task container name

phases:
  pre_build:
    commands:
      - echo "=== PRE-BUILD PHASE ==="

      # Resolve region dynamically
      - REGION=$(aws configure get region || echo $AWS_DEFAULT_REGION)
      - echo "Using region: $REGION"

      # Get AWS account dynamically
      - ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - echo "Account ID: $ACCOUNT_ID"

      # Validate ECR_REPOSITORY variable is passed from project
      - |
        if [ -z "$ECR_REPOSITORY" ]; then
          echo "ERROR: ECR_REPOSITORY not set."
          exit 1
        fi

      # Build repository URI dynamically
      - REPOSITORY_URI=$ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$ECR_REPOSITORY
      - echo "Repository URI: $REPOSITORY_URI"

      # Login to ECR
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com

  build:
    commands:
      - echo "=== BUILD PHASE ==="

      # If IMAGE_TAG not set, use commit ID
      - |
        if [ -z "$IMAGE_TAG" ]; then
          IMAGE_TAG=${CODEBUILD_RESOLVED_SOURCE_VERSION}
        fi

      # Fallback if commit ID missing
      - |
        if [ -z "$IMAGE_TAG" ]; then
          IMAGE_TAG=latest
        fi

      - echo "Final image tag: $IMAGE_TAG"

      # Build & Tag
      - docker build -t $ECR_REPOSITORY:$IMAGE_TAG .
      - docker tag $ECR_REPOSITORY:$IMAGE_TAG $REPOSITORY_URI:$IMAGE_TAG

  post_build:
    commands:
      - echo "=== POST-BUILD PHASE ==="

      - echo "Pushing image..."
      - docker push $REPOSITORY_URI:$IMAGE_TAG

      # Validate container name
      - |
        if [ -z "$CONTAINER_NAME" ]; then
          echo "ERROR: CONTAINER_NAME not set."
          exit 1
        fi

      # Generate imagedefinitions.json dynamically
      - printf '[{"name":"%s","imageUri":"%s"}]' "$CONTAINER_NAME" "$REPOSITORY_URI:$IMAGE_TAG" > imagedefinitions.json

      - echo "Image pushed successfully: $REPOSITORY_URI:$IMAGE_TAG"

artifacts:
  files:
    - imagedefinitions.json

cache:
  paths:
    - '/root/.npm/**/*'
    - '/root/.cache/pip/**/*'
