version: 0.2

env:
  variables:
    ECR_REPOSITORY: "node-image"
    IMAGE_TAG: "latest"

phases:
  pre_build:
    commands:
      - echo "Pre-build: logging into ECR and preparing repository"
      - echo "Region: ${AWS_DEFAULT_REGION:-us-east-1}"
      - REGION=${AWS_DEFAULT_REGION:-us-east-1}
      - ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - REPOSITORY_URI=$ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$ECR_REPOSITORY
      - echo "Repository URI: $REPOSITORY_URI"
      - echo "Logging in to ECR"
      - aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com
     

  build:
    commands:
      - echo "Build phase: building Docker image"
      - echo "Using IMAGE_TAG=${IMAGE_TAG} (override in project env if needed)"
      - if [ -n "$CODEBUILD_RESOLVED_SOURCE_VERSION" ]; then IMAGE_TAG=${CODEBUILD_RESOLVED_SOURCE_VERSION}; fi
      - echo "Final image tag: $IMAGE_TAG"
      - docker build -t $ECR_REPOSITORY:$IMAGE_TAG .
      - docker tag $ECR_REPOSITORY:$IMAGE_TAG $REPOSITORY_URI:$IMAGE_TAG

  post_build:
    commands:
      - echo "Post-build: pushing image to ECR"
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo "Writing imagedefinitions.json"
      - printf '[{"name":"%s","imageUri":"%s"}]' "$ECR_REPOSITORY" "$REPOSITORY_URI:$IMAGE_TAG" > imagedefinitions.json
      - echo "Image pushed: $REPOSITORY_URI:$IMAGE_TAG"

artifacts:
  files:
    - imagedefinitions.json

cache:
  paths:
    - '/root/.npm/**/*'
    - '/root/.cache/pip/**/*'
    timeout-in-minutes: 60

    reports:
      unit-tests:
        files:
          - 'test-results/**/*.xml'
        base-directory: 'test-results'
        discard-paths: no